version: '3.6'
services:
  db:
      image: mariadb:10.1
      container_name: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: password#dd
#     volumes:
#        - ${PWD}/mariadb:/var/lib/mysql
      volumes:
        - maria-db:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306
  php:
#      build: ./
#      image: php:7-fpm-alpine
      image: joninjais/php72
      container_name: php72-fpm
      restart: always
      volumes:
        - ./www/:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
  nginx:
      image: nginx:alpine
      container_name: nginx
      restart: always
      volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./www/:/var/www/html    
      ports:
        - 80:80
  pma:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - db:mysql
      restart: always
      ports:
        - 81:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password#dd
  pgdb:
      image: joninjais/pg96db
      container_name: pgdb
      environment:
        POSTGRES_PASSWORD: postgres#dd
#      volumes:
#        - ${PWD}/pgdata:/var/lib/postgresql/data
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
      ports:
        - 5432:5432 
volumes:
  maria-db:
  pgdata:
           
